import { APP_NAME, GOACTO_FULL, GOACTO_SHORT, TEXTBOOK_LEVELS } from "@/lib/constants";
import type { Conversion, TextbookChapter } from "@/lib/types";

/**
 * Generates a formatted Markdown string from a conversion and its chapters.
 */
export function exportToMarkdown(
  conversion: Conversion,
  chapters: TextbookChapter[]
): string {
  const date = new Date(conversion.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [];

  // Title page
  lines.push(`# ${conversion.title}`);
  lines.push("");
  lines.push(`**Source:** ${conversion.source_url}`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**AI Provider:** ${conversion.ai_provider}`);
  lines.push(`**Generated by:** ${APP_NAME}`);
  lines.push("");

  // Table of contents
  lines.push("## Table of Contents");
  lines.push("");

  for (const levelMeta of TEXTBOOK_LEVELS) {
    const levelChapters = chapters.filter((ch) => ch.level === levelMeta.level);
    if (levelChapters.length === 0) continue;

    lines.push(`### Level ${levelMeta.level}: ${levelMeta.name}`);
    lines.push("");
    for (const chapter of levelChapters) {
      lines.push(`- Chapter ${chapter.chapter_number}: ${chapter.title}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");

  // Each level and its chapters
  for (const levelMeta of TEXTBOOK_LEVELS) {
    const levelChapters = chapters.filter((ch) => ch.level === levelMeta.level);
    if (levelChapters.length === 0) continue;

    lines.push(`## Level ${levelMeta.level}: ${levelMeta.name}`);
    lines.push("");
    lines.push(`> ${levelMeta.description}`);
    lines.push("");

    for (const chapter of levelChapters) {
      lines.push(`### Chapter ${chapter.chapter_number}: ${chapter.title}`);
      lines.push("");
      lines.push(chapter.content);
      lines.push("");

      if (chapter.key_concepts && chapter.key_concepts.length > 0) {
        lines.push("#### Key Concepts");
        lines.push("");
        for (const concept of chapter.key_concepts) {
          lines.push(`- ${concept}`);
        }
        lines.push("");
      }
    }

    lines.push("---");
    lines.push("");
  }

  // Footer
  lines.push(`*Generated by ${APP_NAME} | ${GOACTO_SHORT} — ${GOACTO_FULL}*`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Creates a Blob from the markdown content and triggers a file download.
 */
export function downloadMarkdown(filename: string, content: string): void {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = "none";

  document.body.appendChild(anchor);
  anchor.click();

  // Cleanup
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

/**
 * Generates a styled HTML document for print-to-PDF via a hidden iframe.
 */
export function exportToPDF(
  conversion: Conversion,
  chapters: TextbookChapter[]
): void {
  const date = new Date(conversion.created_at).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Build the HTML content
  let tocHtml = "";
  let bodyHtml = "";

  for (const levelMeta of TEXTBOOK_LEVELS) {
    const levelChapters = chapters.filter((ch) => ch.level === levelMeta.level);
    if (levelChapters.length === 0) continue;

    tocHtml += `<h3>Level ${levelMeta.level}: ${levelMeta.name}</h3>`;
    tocHtml += "<ul>";
    for (const chapter of levelChapters) {
      tocHtml += `<li>Chapter ${escapeHtml(String(chapter.chapter_number))}: ${escapeHtml(chapter.title)}</li>`;
    }
    tocHtml += "</ul>";

    bodyHtml += `<div class="level-section">`;
    bodyHtml += `<h2>Level ${levelMeta.level}: ${escapeHtml(levelMeta.name)}</h2>`;
    bodyHtml += `<p class="level-description">${escapeHtml(levelMeta.description)}</p>`;

    for (const chapter of levelChapters) {
      bodyHtml += `<div class="chapter">`;
      bodyHtml += `<h3>Chapter ${escapeHtml(String(chapter.chapter_number))}: ${escapeHtml(chapter.title)}</h3>`;
      bodyHtml += `<div class="chapter-content">${markdownToHtml(chapter.content)}</div>`;

      if (chapter.key_concepts && chapter.key_concepts.length > 0) {
        bodyHtml += `<div class="key-concepts">`;
        bodyHtml += `<h4>Key Concepts</h4>`;
        bodyHtml += `<ul>`;
        for (const concept of chapter.key_concepts) {
          bodyHtml += `<li>${escapeHtml(concept)}</li>`;
        }
        bodyHtml += `</ul>`;
        bodyHtml += `</div>`;
      }

      bodyHtml += `</div>`;
    }

    bodyHtml += `</div>`;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(conversion.title)} - ${APP_NAME}</title>
  <style>
    @page {
      margin: 1in;
      @bottom-center {
        content: "${APP_NAME} by ${GOACTO_SHORT}";
        font-size: 10px;
        color: #888;
      }
    }

    * {
      box-sizing: border-box;
    }

    body {
      font-family: Georgia, "Times New Roman", serif;
      color: #1a1a1a;
      line-height: 1.7;
      font-size: 12pt;
      max-width: 100%;
      margin: 0;
      padding: 0;
    }

    /* Title page */
    .title-page {
      text-align: center;
      padding-top: 3in;
      page-break-after: always;
    }

    .title-page h1 {
      font-size: 28pt;
      margin-bottom: 0.5em;
      color: #111;
    }

    .title-page .subtitle {
      font-size: 14pt;
      color: #555;
      margin-bottom: 2em;
    }

    .title-page .meta {
      font-size: 11pt;
      color: #666;
      line-height: 2;
    }

    .title-page .branding {
      margin-top: 3em;
      font-size: 10pt;
      color: #888;
    }

    .title-page .branding strong {
      color: #555;
    }

    /* Table of contents */
    .toc {
      page-break-after: always;
    }

    .toc h2 {
      font-size: 20pt;
      border-bottom: 2px solid #333;
      padding-bottom: 0.3em;
      margin-bottom: 1em;
    }

    .toc h3 {
      font-size: 13pt;
      color: #333;
      margin-top: 1.2em;
      margin-bottom: 0.4em;
    }

    .toc ul {
      list-style: none;
      padding-left: 1.5em;
      margin: 0;
    }

    .toc li {
      padding: 0.2em 0;
      font-size: 11pt;
      color: #444;
    }

    /* Level sections */
    .level-section {
      page-break-before: always;
    }

    .level-section h2 {
      font-size: 22pt;
      color: #111;
      border-bottom: 2px solid #333;
      padding-bottom: 0.3em;
      margin-bottom: 0.5em;
    }

    .level-description {
      font-style: italic;
      color: #555;
      margin-bottom: 1.5em;
      font-size: 11pt;
    }

    /* Chapters */
    .chapter {
      margin-bottom: 2em;
    }

    .chapter h3 {
      font-size: 16pt;
      color: #222;
      margin-top: 1.5em;
      margin-bottom: 0.5em;
    }

    .chapter-content {
      font-size: 12pt;
    }

    .chapter-content p {
      margin: 0.8em 0;
    }

    .chapter-content h1,
    .chapter-content h2,
    .chapter-content h3,
    .chapter-content h4 {
      color: #222;
      margin-top: 1.2em;
      margin-bottom: 0.4em;
    }

    .chapter-content h1 { font-size: 18pt; }
    .chapter-content h2 { font-size: 15pt; }
    .chapter-content h3 { font-size: 13pt; }
    .chapter-content h4 { font-size: 12pt; }

    .chapter-content ul,
    .chapter-content ol {
      padding-left: 1.5em;
      margin: 0.5em 0;
    }

    .chapter-content li {
      margin: 0.3em 0;
    }

    /* Code blocks */
    .chapter-content pre {
      background-color: #f5f5f5;
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 1em;
      overflow-x: auto;
      font-size: 10pt;
      line-height: 1.5;
      margin: 1em 0;
      page-break-inside: avoid;
    }

    .chapter-content code {
      font-family: "Courier New", Courier, monospace;
      font-size: 10pt;
    }

    .chapter-content p code,
    .chapter-content li code {
      background-color: #f0f0f0;
      padding: 0.15em 0.4em;
      border-radius: 3px;
      font-size: 0.9em;
    }

    /* Blockquotes */
    .chapter-content blockquote {
      border-left: 3px solid #ccc;
      margin: 1em 0;
      padding: 0.5em 1em;
      color: #555;
      font-style: italic;
    }

    /* Tables */
    .chapter-content table {
      border-collapse: collapse;
      width: 100%;
      margin: 1em 0;
      font-size: 11pt;
    }

    .chapter-content th,
    .chapter-content td {
      border: 1px solid #ccc;
      padding: 0.5em 0.8em;
      text-align: left;
    }

    .chapter-content th {
      background-color: #f5f5f5;
      font-weight: bold;
    }

    /* Key concepts */
    .key-concepts {
      margin-top: 1.5em;
      padding: 1em;
      background-color: #fafafa;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
    }

    .key-concepts h4 {
      font-size: 11pt;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: #666;
      margin: 0 0 0.5em 0;
    }

    .key-concepts ul {
      list-style: disc;
      padding-left: 1.5em;
      margin: 0;
    }

    .key-concepts li {
      font-size: 11pt;
      padding: 0.15em 0;
      color: #444;
    }

    /* Footer */
    .print-footer {
      text-align: center;
      font-size: 10pt;
      color: #888;
      margin-top: 3em;
      padding-top: 1em;
      border-top: 1px solid #ddd;
    }

    @media print {
      body {
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
    }
  </style>
</head>
<body>
  <!-- Title page -->
  <div class="title-page">
    <h1>${escapeHtml(conversion.title)}</h1>
    <div class="subtitle">A Learning Textbook</div>
    <div class="meta">
      <div>Source: ${escapeHtml(conversion.source_url)}</div>
      <div>Date: ${escapeHtml(date)}</div>
      <div>AI Provider: ${escapeHtml(conversion.ai_provider)}</div>
    </div>
    <div class="branding">
      <strong>${APP_NAME}</strong> by <strong>${GOACTO_SHORT}</strong><br>
      ${GOACTO_FULL}
    </div>
  </div>

  <!-- Table of contents -->
  <div class="toc">
    <h2>Table of Contents</h2>
    ${tocHtml}
  </div>

  <!-- Content -->
  ${bodyHtml}

  <!-- Footer -->
  <div class="print-footer">
    ${APP_NAME} by ${GOACTO_SHORT} &mdash; ${GOACTO_FULL}
  </div>
</body>
</html>`;

  // Create hidden iframe, write HTML, and trigger print
  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "none";

  document.body.appendChild(iframe);

  const iframeDoc = iframe.contentWindow?.document;
  if (!iframeDoc) {
    document.body.removeChild(iframe);
    return;
  }

  iframeDoc.open();
  iframeDoc.write(html);
  iframeDoc.close();

  // Wait for content to render, then print
  iframe.onload = () => {
    setTimeout(() => {
      iframe.contentWindow?.print();
      // Remove iframe after print dialog closes
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 1000);
    }, 250);
  };

  // Fallback: if onload doesn't fire (content already loaded via write)
  setTimeout(() => {
    if (document.body.contains(iframe)) {
      try {
        iframe.contentWindow?.print();
      } catch {
        // Print may have already been triggered
      }
      setTimeout(() => {
        if (document.body.contains(iframe)) {
          document.body.removeChild(iframe);
        }
      }, 1000);
    }
  }, 1000);
}

/**
 * Escapes HTML special characters to prevent XSS.
 */
function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (char) => map[char]);
}

/**
 * Simple markdown-to-HTML converter for PDF export.
 * Handles common markdown patterns without external dependencies.
 */
function markdownToHtml(markdown: string): string {
  let html = markdown;

  // Escape HTML in the raw text first, but preserve markdown syntax
  // We process block-level elements first, then inline

  // Code blocks (fenced) — must be done before escaping
  const codeBlocks: string[] = [];
  html = html.replace(/```(\w*)\n([\s\S]*?)```/g, (_match, _lang, code) => {
    const index = codeBlocks.length;
    codeBlocks.push(`<pre><code>${escapeHtml(code.trimEnd())}</code></pre>`);
    return `%%CODEBLOCK_${index}%%`;
  });

  // Inline code — must be done before escaping
  const inlineCodes: string[] = [];
  html = html.replace(/`([^`]+)`/g, (_match, code) => {
    const index = inlineCodes.length;
    inlineCodes.push(`<code>${escapeHtml(code)}</code>`);
    return `%%INLINECODE_${index}%%`;
  });

  // Now escape remaining HTML
  html = escapeHtml(html);

  // Restore code blocks and inline codes
  codeBlocks.forEach((block, i) => {
    html = html.replace(`%%CODEBLOCK_${i}%%`, block);
  });
  inlineCodes.forEach((code, i) => {
    html = html.replace(`%%INLINECODE_${i}%%`, code);
  });

  // Headings
  html = html.replace(/^#### (.+)$/gm, "<h4>$1</h4>");
  html = html.replace(/^### (.+)$/gm, "<h3>$1</h3>");
  html = html.replace(/^## (.+)$/gm, "<h2>$1</h2>");
  html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

  // Blockquotes
  html = html.replace(/^&gt; (.+)$/gm, "<blockquote>$1</blockquote>");

  // Bold and italic
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, "<strong><em>$1</em></strong>");
  html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
  html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");

  // Links
  html = html.replace(
    /\[([^\]]+)\]\(([^)]+)\)/g,
    '<a href="$2">$1</a>'
  );

  // Horizontal rules
  html = html.replace(/^---$/gm, "<hr>");

  // Unordered lists
  html = html.replace(/^(\s*)[-*+] (.+)$/gm, "$1<li>$2</li>");

  // Ordered lists
  html = html.replace(/^(\s*)\d+\. (.+)$/gm, "$1<li>$2</li>");

  // Wrap consecutive <li> elements in <ul>
  html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>");

  // Paragraphs — wrap lines not already in block elements
  const blockTags = ["<h", "<ul", "<ol", "<pre", "<blockquote", "<hr", "<li", "<div", "<table"];
  const processedLines = html.split("\n");
  const outputLines: string[] = [];
  let inParagraph = false;

  for (const line of processedLines) {
    const trimmed = line.trim();

    if (trimmed === "") {
      if (inParagraph) {
        outputLines.push("</p>");
        inParagraph = false;
      }
      continue;
    }

    const isBlockElement = blockTags.some((tag) => trimmed.startsWith(tag));

    if (isBlockElement) {
      if (inParagraph) {
        outputLines.push("</p>");
        inParagraph = false;
      }
      outputLines.push(trimmed);
    } else {
      if (!inParagraph) {
        outputLines.push("<p>");
        inParagraph = true;
      }
      outputLines.push(trimmed);
    }
  }

  if (inParagraph) {
    outputLines.push("</p>");
  }

  return outputLines.join("\n");
}
